# Site settings
title: Personal Website
email: pahafenb@edu.uwaterloo.ca
description: A comprehenisve add-on to my resume> # this means to ignore newlines until "baseurl:"
baseurl: "patrickhafenberg.me # the subpath of your site, e.g. /blog/
url: "patrickhafenberg.me" # the base hostname & protocol for your site

github_username: pahafenb

# Build settings
markdown: kramdown
